name: CI

on: [push, pull_request]

jobs:

  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        typo3: ['^9', '^10']
        php: ['7.2', '7.3', '7.4']
        mysql: ['5.7']
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up MySQL ${{ matrix.mysql }}
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: ${{ matrix.mysql }}
        mysql root password: 'root'
    - name: Set up PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
    - name: Install
      run: |
        composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
        git checkout composer.json
    - name: Lint
      run: |
        composer test:php:lint
    - name: CGL
      run: |
        composer cgl:ci
    - name: Unit Tests
      run: |
        composer test:php:unit
    - name: Functional Tests
      run: |
        composer test:php:functional
      env:
        COMPOSER_PROCESS_TIMEOUT: 1200
        typo3DatabaseHost: 127.0.0.1
        typo3DatabaseName: t3func
        typo3DatabasePassword: root
        typo3DatabaseUsername: root

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Install
      run: |
        cd Build
        yarn install
    - name: Build
      run: |
        cd Build
        yarn build
