name: CI

on: [push, pull_request]

jobs:

  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        typo3: ['^8', '^9']
        php: ['7.2']
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up PHP Version ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:2.2
    - name: Install
      run: |
        composer require typo3/minimal:${{ matrix.typo3 }} --no-progress
        git checkout composer.json
    - name: Lint
      run: composer test:php:lint
    - name: CGL
      run: composer cgl
    - name: Unit Tests
      run: composer test:php:unit

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'
    - name: Install
      run: |
        cd Build
        yarn install
    - name: Build
      run: |
        cd Build
        yarn build
